use serde::Serialize;

#[derive(Debug, Serialize, Clone)]
pub enum PostgreSQLType {
    Text,
    Char(i32),
    VarChar(i32),
    Bit(i32),
    VarBit,
    UUID,
    Xml,
    Inet,
    Boolean,
    Integer,
    SmallInt,
    Int,
    BigInt,
    Oid,
    DoublePrecision,
    Real,
    Decimal(i32, i32),
    Money,
    Date,
    Timestamp(i32, bool),
    Time(bool),
    Json,
    JsonB,
    ByteA,
    Array(Box<PostgreSQLType>),
}
