pub enum MySQLType {
    VarChar(i32),
    Text,
    Char(i32),
    TinyText,
    MediumText,
    LongText,
    Bit(i32),
    TinyInt(i32, bool),
    Int(bool),
    SmallInt(bool),
    MediumInt(bool),
    BigInt(bool),
    Year,
    Float,
    Double,
    Decimal(i32, i32),
    DateTime(i32),
    Date(i32),
    Time(i32),
    Timestamp(i32),
    Json,
    LongBlob,
    Binary,
    VarBinary,
    TinyBlob,
    Blob,
    MediumBlob,
}
